vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: /uploads/product_images
            upload_destination: '%kernel.project_dir%/public/uploads/product_images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        manufacturer_logos:
            uri_prefix: /uploads/manufacturers
            upload_destination: '%kernel.project_dir%/public/uploads/manufacturers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        news_images:
            uri_prefix: /uploads/news
            upload_destination: '%kernel.project_dir%/public/uploads/news'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true