vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
